 # load largemodel bin file
model_bin = open('./LocalModel/pytorch_model.bin', 'wb')
shard = open('./LocalModel/shards/01_shard_pytorch_model.bin', 'rb')
model_bin.write(shard.read())
shard.close()
shard = open('./LocalModel/shards/02_shard_pytorch_model.bin', 'rb')
model_bin.write(shard.read())
shard.close()
shard = open('./LocalModel/shards/03_shard_pytorch_model.bin', 'rb')
model_bin.write(shard.read())
shard.close()
shard = open('./LocalModel/shards/04_shard_pytorch_model.bin', 'rb')
model_bin.write(shard.read())
shard.close()
model_bin.close()