[connections.snowpark]
account = "zs31584.east-us-2.azure"
user = "lwahlert"
password = "JSKDFJ&7#^dfd"
role = "ARMETA_AI_ROLE"
warehouse = "ARMETA_AI_WH"
database = "ARMETA_AI"
schema = "PC"
client_session_keep_alive = true